services:
  postgres:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: subscription_service
      POSTGRES_PASSWORD: 92QMNMKVPee
      POSTGRES_DB: subsservice
    ports:
      - 5431:5432
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: event_service
      MONGO_INITDB_ROOT_PASSWORD: Y585wKkKZp95xrwq

    ports:
      - 27018:27017