services:
  postgres:
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: subscription_service
      POSTGRES_PASSWORD: 92QMNMKVPee
      POSTGRES_DB: subsservice
    ports:
      - 5431:5432